# -*- coding: utf-8 -*-
"""Copy of SPAM.CSV

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rRxPP0xz9tSPCML69zP-MFVWQLL1L6E
"""

# Use a pipeline as a high-level helper
from transformers import pipeline

pipe = pipeline("text-classification", model="mrm8488/bert-tiny-finetuned-sms-spam-detection")

# Load model directly
from transformers import AutoTokenizer, AutoModelForSequenceClassification

tokenizer = AutoTokenizer.from_pretrained("mrm8488/bert-tiny-finetuned-sms-spam-detection")
model = AutoModelForSequenceClassification.from_pretrained("mrm8488/bert-tiny-finetuned-sms-spam-detection")

import streamlit as st

import streamlit as st
from transformers import pipeline, AutoTokenizer, AutoModelForSequenceClassification

def main():
    st.title("Text Classification App")
    st.write("This app uses a pretrained model to classify text.")


    # Text input
    text_input = st.text_area("Enter text to classify", "")

    if st.button("Classify"):
        if text_input:
            # Perform classification
            result = pipe(text_input)

            # Display result
            st.write("Predicted Class:", result[0]['label'])
            st.write("Confidence Score:", result[0]['score'])
        else:
            st.warning("Please enter some text to classify.")

if __name__ == "__main__":
    main()